In [1]:
import pandas as pd

In [2]:
mvps = pd.read_csv('data/mvps.csv')

In [3]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,7,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
482,8,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
483,9,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
484,10,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
485,11,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

In [4]:
mvps = mvps[['Player', 'Year', 'Pts Won', 'Pts Max', 'Share']]

In [5]:
mvps

              Player  Year  Pts Won  Pts Max  Share
0     Michael Jordan  1991    891.0      960  0.928
1      Magic Johnson  1991    497.0      960  0.518
2     David Robinson  1991    476.0      960  0.496
3    Charles Barkley  1991    222.0      960  0.231
4        Karl Malone  1991    142.0      960  0.148
..               ...   ...      ...      ...    ...
481    Stephen Curry  2022      4.0     1000  0.004
482       Chris Paul  2022      2.0     1000  0.002
483    DeMar DeRozan  2022      1.0     1000  0.001
484     Kevin Durant  2022      1.0     1000  0.001
485     LeBron James  2022      1.0     1000  0.001

[486 rows x 5 columns]

In [6]:
players = pd.read_csv('data/players.csv')

In [7]:
players.head(25)

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
5,5,6,Danny Ainge,SG,31,POR,80,0,21.4,4.2,...,0.6,2.0,2.6,3.6,0.8,0.2,1.3,2.4,11.1,1991
6,6,7,Mark Alarie,PF,27,WSB,42,1,14.0,2.4,...,1.0,1.8,2.8,1.1,0.4,0.2,1.0,2.1,5.8,1991
7,7,8,Steve Alford,PG,26,DAL,34,0,6.9,1.7,...,0.3,0.4,0.7,0.6,0.2,0.0,0.5,0.3,4.4,1991
8,8,9,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,9,9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,10,9,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,11,9,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991
12,12,10,Nick Anderson,SG,23,ORL,70,42,28.2,5.7,...,1.3,4.2,5.5,1.5,1.1,0.6,1.6,2.1,14.1,1991
13,13,11,Ron Anderson,SF,32,PHI,82,13,28.5,6.2,...,1.3,3.2,4.5,1.4,0.8,0.2,1.2,2.0,14.6,1991
14,14,12,Willie Anderson,SG,24,SAS,75,75,34.6,6.0,...,0.9,3.8,4.7,4.8,1.1,0.6,2.2,3.0,14.4,1991
15,15,13,Michael Ansley,SF,23,ORL,67,1,13.1,2.1,...,1.8,2.0,3.8,0.4,0.4,0.1,0.5,1.9,5.7,1991
16,16,14,B.J. Armstrong,PG,23,CHI,82,0,21.1,3.7,...,0.3,1.5,1.8,3.7,0.9,0.0,1.3,1.4,8.8,1991
17,17,15,Vincent Askew,SG,24,GSW,7,0,12.1,1.7,...,1.0,0.6,1.6,1.9,0.3,0.0,0.9,3.0,4.7,1991
18,18,16,Keith Askins,SF,23,MIA,39,1,6.8,0.9,...,0.8,1.0,1.7,0.5,0.4,0.3,0.3,1.2,2.2,1991
19,19,17,Miloš Babić,PF,22,CLE,12,0,4.3,0.5,...,0.5,0.3,0.8,0.3,0.1,0.1,0.4,0.6,1.6,1991
20,20,18,Thurl Bailey,PF,29,UTA,82,22,30.3,4.9,...,1.2,3.7,5.0,1.5,0.6,1.1,1.6,2.0,12.4,1991
21,21,19,Cedric Ball,PF,22,LAC,7,0,3.7,0.4,...,0.7,0.9,1.6,0.0,0.0,0.3,0.3,0.7,1.1,1991
22,22,20,Ken Bannister,PF,30,LAC,47,3,7.2,0.9,...,0.7,1.3,2.0,0.2,0.1,0.1,0.5,1.6,2.4,1991
23,23,21,Charles Barkley*,SF,27,PHI,67,67,37.3,9.9,...,3.9,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,1991
24,24,22,Dana Barros,PG,23,SEA,66,0,11.4,2.3,...,0.3,0.8,1.1,1.7,0.3,0.0,0.8,0.6,6.3,1991

In [8]:
players = players.drop(columns=['Unnamed: 0', 'Rk'])

In [9]:
players['Player'] = players['Player'].str.replace('*', '', regex=False)

In [10]:
players[players['Player'] == 'Greg Anderson']

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,2.8,.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,4.7,.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991
467,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1412,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
1911,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2381,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
2948,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3541,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [11]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df['Tm'] == 'TOT']
        row['Tm'] = df.iloc[-1,:]['Tm']
        return row
    
players = players.groupby(['Player', 'Year']).apply(single_row)

In [12]:
players[players['Player'] == 'Greg Anderson']

                                Player Pos Age   Tm   G  GS    MP   FG   FGA  \
Player        Year
Greg Anderson 1991 8     Greg Anderson  PF  26  DEN  68   2  13.6  1.7   4.0
              1992 467   Greg Anderson  PF  27  DEN  82  82  34.1  4.7  10.4
              1994 1412  Greg Anderson  PF  29  DET  77  47  21.1  2.6   4.8
              1995 1911  Greg Anderson  PF  30  ATL  51   0  12.2  1.1   2.0
              1996 2381  Greg Anderson  PF  31  SAS  46   7   7.5  0.5   1.0
              1997 2948  Greg Anderson   C  32  SAS  82  48  20.2  1.6   3.2
              1998 3541  Greg Anderson   C  33  ATL  50   0   8.0  0.7   1.6

                          FG%  ...  ORB  DRB   TRB  AST  STL  BLK  TOV   PF  \
Player        Year             ...
Greg Anderson 1991 8     .430  ...  1.4  3.3   4.7  0.2  0.5  0.7  1.2  2.1
              1992 467   .456  ...  4.1  7.4  11.5  1.0  1.1  0.8  2.5  3.2
              1994 1412  .543  ...  2.4  5.0   7.4  0.7  0.7  0.9  1.2  3.0
              1995 1911  .548  ...  1.2  2.5   3.7  0.3  0.5  0.6  0.6  2.0
              1996 2381  .511  ...  0.6  1.5   2.2  0.2  0.2  0.5  0.5  1.4
              1997 2948  .496  ...  1.9  3.5   5.5  0.4  0.8  0.8  0.9  2.7
              1998 3541  .444  ...  0.8  1.6   2.4  0.3  0.4  0.2  0.3  1.7

                          PTS  Year
Player        Year
Greg Anderson 1991 8      4.3  1991
              1992 467   11.5  1992
              1994 1412   6.4  1994
              1995 1911   2.9  1995
              1996 2381   1.2  1996
              1997 2948   3.9  1997
              1998 3541   1.8  1998

[7 rows x 30 columns]

In [13]:
players.index = players.index.droplevel()
players.index = players.index.droplevel()

In [14]:
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
164,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
633,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
1092,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
1579,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
2067,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6095,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
6595,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
7176,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,1.0,1.5,2.4,0.3,0.2,0.5,0.7,2.2,3.8,2004
7776,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
8370,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [15]:
combined = players.merge(mvps, how='outer', on=['Player', 'Year'])

In [16]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,NaN,NaN,NaN
14693,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,NaN,NaN,NaN
14694,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,NaN,NaN,NaN
14695,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,NaN,NaN,NaN
14696,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,NaN,NaN,NaN

In [17]:
combined[['Pts Won', 'Pts Max', 'Share']] = combined[['Pts Won', 'Pts Max', 'Share']].fillna(0)

In [18]:
combined

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
14693,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
14694,Željko Rebrača,C,31,ATL,24,2,11.4,1.4,3.2,.442,...,0.3,0.2,0.5,0.7,2.2,3.8,2004,0.0,0.0,0.0
14695,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
14696,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [19]:
teams = pd.read_csv('data/teams.csv')

In [20]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1063,13,56,26,.683,—,115.6,109.9,5.37,2022,Memphis Grizzlies*
1064,14,52,30,.634,4.0,108.0,104.7,3.12,2022,Dallas Mavericks*
1065,15,36,46,.439,20.0,109.3,110.3,-0.84,2022,New Orleans Pelicans*
1066,16,34,48,.415,22.0,113.2,113.0,0.02,2022,San Antonio Spurs
1067,17,20,62,.244,36.0,109.7,118.2,-8.26,2022,Houston Rockets

In [21]:
del teams['Unnamed: 0']

In [22]:
teams = teams[~teams['W'].str.contains('Division')].copy()

In [23]:
teams['Team'] = teams['Team'].str.replace('*', '', regex=False)

teams['GB'] = teams['GB'].str.replace('—', '0')

In [24]:
teams

       W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0     56  26  .683     0  111.5  105.7   5.22  1991        Boston Celtics
1     44  38  .537  12.0  105.4  105.6  -0.39  1991    Philadelphia 76ers
2     39  43  .476  17.0  103.1  103.3  -0.43  1991       New York Knicks
3     30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4     26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
...   ..  ..   ...   ...    ...    ...    ...   ...                   ...
1063  56  26  .683     0  115.6  109.9   5.37  2022     Memphis Grizzlies
1064  52  30  .634   4.0  108.0  104.7   3.12  2022      Dallas Mavericks
1065  36  46  .439  20.0  109.3  110.3  -0.84  2022  New Orleans Pelicans
1066  34  48  .415  22.0  113.2  113.0   0.02  2022     San Antonio Spurs
1067  20  62  .244  36.0  109.7  118.2  -8.26  2022       Houston Rockets

[936 rows x 9 columns]

In [25]:
combined['Tm'].nunique() == teams['Team'].nunique()

False

In [26]:
sorted(combined['Tm'].unique())

['ATL',
 'BOS',
 'BRK',
 'CHA',
 'CHH',
 'CHI',
 'CHO',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NJN',
 'NOH',
 'NOK',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHO',
 'POR',
 'SAC',
 'SAS',
 'SEA',
 'TOR',
 'UTA',
 'VAN',
 'WAS',
 'WSB']

In [27]:
sorted(teams['Team'].unique())

['Atlanta Hawks',
 'Boston Celtics',
 'Brooklyn Nets',
 'Charlotte Bobcats',
 'Charlotte Hornets',
 'Chicago Bulls',
 'Cleveland Cavaliers',
 'Dallas Mavericks',
 'Denver Nuggets',
 'Detroit Pistons',
 'Golden State Warriors',
 'Houston Rockets',
 'Indiana Pacers',
 'Los Angeles Clippers',
 'Los Angeles Lakers',
 'Memphis Grizzlies',
 'Miami Heat',
 'Milwaukee Bucks',
 'Minnesota Timberwolves',
 'New Jersey Nets',
 'New Orleans Hornets',
 'New Orleans Pelicans',
 'New Orleans/Oklahoma City Hornets',
 'New York Knicks',
 'Oklahoma City Thunder',
 'Orlando Magic',
 'Philadelphia 76ers',
 'Phoenix Suns',
 'Portland Trail Blazers',
 'Sacramento Kings',
 'San Antonio Spurs',
 'Seattle SuperSonics',
 'Toronto Raptors',
 'Utah Jazz',
 'Vancouver Grizzlies',
 'Washington Bullets',
 'Washington Wizards']

In [28]:
combined['Tm'] = combined['Tm'].str.replace('CHO', 'CHH')

In [29]:
combined['Tm'].nunique() == teams['Team'].nunique()

True

In [30]:
abbr = pd.DataFrame()

abbr['Team'] = sorted(teams['Team'].unique())
abbr['Tm'] = sorted(combined['Tm'].unique())

abbr.iloc[[21],[0]] = 'New Orleans/Oklahoma City Hornets'
abbr.iloc[[22],[0]] = 'New Orleans Pelicans'

abbr.iloc[[35],[0]] = 'Washington Wizards'
abbr.iloc[[36],[0]] = 'Washington Bullets'

abbr.to_csv('data/NBA_abbreviations.csv')

In [31]:
abbr

                                 Team   Tm
0                       Atlanta Hawks  ATL
1                      Boston Celtics  BOS
2                       Brooklyn Nets  BRK
3                   Charlotte Bobcats  CHA
4                   Charlotte Hornets  CHH
5                       Chicago Bulls  CHI
6                 Cleveland Cavaliers  CLE
7                    Dallas Mavericks  DAL
8                      Denver Nuggets  DEN
9                     Detroit Pistons  DET
10              Golden State Warriors  GSW
11                    Houston Rockets  HOU
12                     Indiana Pacers  IND
13               Los Angeles Clippers  LAC
14                 Los Angeles Lakers  LAL
15                  Memphis Grizzlies  MEM
16                         Miami Heat  MIA
17                    Milwaukee Bucks  MIL
18             Minnesota Timberwolves  MIN
19                    New Jersey Nets  NJN
20                New Orleans Hornets  NOH
21  New Orleans/Oklahoma City Hornets  NOK
22               New Orleans Pelicans  NOP
23                    New York Knicks  NYK
24              Oklahoma City Thunder  OKC
25                      Orlando Magic  ORL
26                 Philadelphia 76ers  PHI
27                       Phoenix Suns  PHO
28             Portland Trail Blazers  POR
29                   Sacramento Kings  SAC
30                  San Antonio Spurs  SAS
31                Seattle SuperSonics  SEA
32                    Toronto Raptors  TOR
33                          Utah Jazz  UTA
34                Vancouver Grizzlies  VAN
35                 Washington Wizards  WAS
36                 Washington Bullets  WSB

In [32]:
teams = teams.merge(abbr, how='left', on='Team')

In [33]:
teams

      W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team   Tm
0    56  26  .683     0  111.5  105.7   5.22  1991        Boston Celtics  BOS
1    44  38  .537  12.0  105.4  105.6  -0.39  1991    Philadelphia 76ers  PHI
2    39  43  .476  17.0  103.1  103.3  -0.43  1991       New York Knicks  NYK
3    30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets  WSB
4    26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets  NJN
..   ..  ..   ...   ...    ...    ...    ...   ...                   ...  ...
931  56  26  .683     0  115.6  109.9   5.37  2022     Memphis Grizzlies  MEM
932  52  30  .634   4.0  108.0  104.7   3.12  2022      Dallas Mavericks  DAL
933  36  46  .439  20.0  109.3  110.3  -0.84  2022  New Orleans Pelicans  NOP
934  34  48  .415  22.0  113.2  113.0   0.02  2022     San Antonio Spurs  SAS
935  20  62  .244  36.0  109.7  118.2  -8.26  2022       Houston Rockets  HOU

[936 rows x 10 columns]

In [34]:
stats = combined.merge(teams, how='outer', on=['Tm', 'Year'])

In [35]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,W,L,W/L%,GB,PS/G,PA/G,SRS,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,0.0,58,24,.707,5.0,106.3,99.6,6.73,Los Angeles Lakers
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,0.0,58,24,.707,5.0,106.3,99.6,6.73,Los Angeles Lakers
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,0.0,58,24,.707,5.0,106.3,99.6,6.73,Los Angeles Lakers
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,0.0,58,24,.707,5.0,106.3,99.6,6.73,Los Angeles Lakers
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,0.0,58,24,.707,5.0,106.3,99.6,6.73,Los Angeles Lakers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14692,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,.484,...,0.0,0.0,42,40,.512,9.0,103.6,103.8,-0.45,Milwaukee Bucks
14693,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,.286,...,0.0,0.0,42,40,.512,9.0,103.6,103.8,-0.45,Milwaukee Bucks
14694,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,.470,...,0.0,0.0,42,40,.512,9.0,103.6,103.8,-0.45,Milwaukee Bucks
14695,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,.459,...,0.0,0.0,42,40,.512,9.0,103.6,103.8,-0.45,Milwaukee Bucks
14696,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,.455,...,0.0,0.0,42,40,.512,9.0,103.6,103.8,-0.45,Milwaukee Bucks

In [36]:
stats.dtypes

Player      object
Pos         object
Age         object
Tm          object
G           object
GS          object
MP          object
FG          object
FGA         object
FG%         object
3P          object
3PA         object
3P%         object
2P          object
2PA         object
2P%         object
eFG%        object
FT          object
FTA         object
FT%         object
ORB         object
DRB         object
TRB         object
AST         object
STL         object
BLK         object
TOV         object
PF          object
PTS         object
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
Team        object
dtype: object

In [37]:
stats = stats.apply(pd.to_numeric, errors='ignore')

In [38]:
stats.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
W            int64
L            int64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
Team        object
dtype: object

In [39]:
stats.to_csv('data/player_mvp_stats.csv')